<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit417fc68852b7c9172a271eb606edc81f
{
    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {

        }, null, ClassLoader::class);
    }
}
